sudo: required
services:
    - docker:

before install:
    - docker build -t jt10/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run jt10/react-test npm test -- --coverage

after_success:
    - docker build -t jt10/multi-client ./client
    - docker build -t jt10/multi-nginx ./nginx
    - docker build -t jt10/multi-server ./server
    - docker build -t jt10/multi-worker ./worker
    # Log into docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take images and push to docker hub
    - docker push jt10/multi-client
    - docker push jt10/multi-nginx
    - docker push jt10/multi-server
    - docker push jt10/multi-worker 
    
    


